/* Create Tables */

CREATE TABLE CRAWLING
(
	C_NUM NUMBER NOT NULL,
	C_NAME NUMBER NOT NULL,
	C_INFO VARCHAR2(2500) NOT NULL,
	PRIMARY KEY (C_NUM)
);


CREATE TABLE LISTS
(
	L_NUM NUMBER NOT NULL,
	L_PID NUMBER NOT NULL,
	L_MID VARCHAR2(20) NOT NULL,
	PRIMARY KEY (L_NUM)
);


CREATE TABLE MEMBERS
(
	M_ID VARCHAR2(20) NOT NULL,
	M_PW VARCHAR2(30) NOT NULL,
	M_NAME VARCHAR2(20) NOT NULL,
	M_EMAIL1 VARCHAR2(30) NOT NULL,
	M_EMAIL2 VARCHAR2(30) NOT NULL,
	M_NUM VARCHAR2(20) NOT NULL,
	M_REGDATE DATE NOT NULL,
	PRIMARY KEY (M_ID)
);


CREATE TABLE MYFUNDING
(
	MF_NUM NUMBER NOT NULL,
	MF_MID VARCHAR2(20) NOT NULL,
	MF_PID NUMBER NOT NULL,
	PRIMARY KEY (MF_NUM)
);


CREATE TABLE MYLIKE
(
	ML_NUM NUMBER NOT NULL,
	ML_MID VARCHAR2(20) NOT NULL,
	ML_PID NUMBER NOT NULL,
	PRIMARY KEY (ML_NUM)
);


CREATE TABLE PRODUCT
(
	P_NUM NUMBER NOT NULL,
	P_NAME VARCHAR2(50) NOT NULL,
	P_PRICE NUMBER NOT NULL,
	P_INFO VARCHAR2(4000) NOT NULL,
	P_FINISH NUMBER DEFAULT 0 NOT NULL,
	P_IMAGE1 VARCHAR2(3000) NOT NULL,
	P_IMAGE2 VARCHAR2(3000) NOT NULL,
	P_IMAGE3 VARCHAR2(3000) NOT NULL,
	P_AMOUNT NUMBER NOT NULL,
	P_CRNAMOUNT NUMBER DEFAULT 0 NOT NULL,
	P_PERCENT NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY (P_NUM)
);



/* Create Foreign Keys */

ALTER TABLE LISTS
	ADD FOREIGN KEY (L_MID)
	REFERENCES MEMBERS (M_ID)
;


ALTER TABLE MYFUNDING
	ADD FOREIGN KEY (MF_MID)
	REFERENCES MEMBERS (M_ID)
;


ALTER TABLE MYLIKE
	ADD FOREIGN KEY (ML_MID)
	REFERENCES MEMBERS (M_ID)
;


ALTER TABLE CRAWLING
	ADD FOREIGN KEY (C_NAME)
	REFERENCES PRODUCT (P_NUM)
;


ALTER TABLE LISTS
	ADD FOREIGN KEY (L_PID)
	REFERENCES PRODUCT (P_NUM)
;


ALTER TABLE MYFUNDING
	ADD FOREIGN KEY (MF_PID)
	REFERENCES PRODUCT (P_NUM)
;


ALTER TABLE MYLIKE
	ADD FOREIGN KEY (ML_PID)
	REFERENCES PRODUCT (P_NUM)
;


/* Drop Tables */

DROP TABLE CRAWLING CASCADE CONSTRAINTS;
DROP TABLE LISTS CASCADE CONSTRAINTS;
DROP TABLE MYFUNDING CASCADE CONSTRAINTS;
DROP TABLE MYLIKE CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;